version: "3.8"

services:
  tt-workspace:
    build:
      context: ./workspace/
      dockerfile: Dockerfile
    container_name: "workspace"
    ports:
      - "30303:30303"
      - "8545:8545"
    tty: true
    privileged: true
    volumes:
      - ../../src:/src